name: speech
dependencies:
  - python=3.7
  - pyaudio=0.2.11
  - six=1.12.0
  - pandas=0.23.4
  - gensim=3.7.1
  - textblob=0.15.2
  - nibabel=2.3.3
  - nipype=1.1.8
  - pip:
    - google-cloud-speech==0.36.3
    - g2p_en==1.0.1
